resourcepack:
  url: https://drive.google.com/uc?export=download&id=1hFbCFVEp4NbYBfcXnQ4-8-xYnDkYM1Nb
  hash: 1674dcd21ac4d142b1116ddf4de683605fec845c

rankings:
  sushida:
    title: 寿司打お勧めコースランキング
    scoreboard: sushida.regular
    word: word
    rule: time
    settings:
      level: 2
      time: 120
      timeout: 6

aroundyou:
  enabled: true